### ISSUE TITLE
Question about consul in kubernetes

### ISSUE THREAD

**Issue by Evgen787** [drud/vault-consul-on-kube#22]
Hi, where is this variable defined?
 - "-advertise=$(CONSUL_1_SERVICE_HOST)"
_vault-consul-on-kube/deployments/consul-1.yaml_

How to advertise NODE IP to consul -advertise=<NODE_IP_ADDR> in kubernetes/rancher?
When app running, it go to consul client and register svc in consul server, but containter have internal IP,  and me need set -advertise to NODE_IP_ADDR.

**Comment by rfay** [comment]
Hi @Evgen787 - Kubernetes sets quite a number of environment variables magically in each container. Info at https://kubernetes.io/docs/concepts/containers/container-environment-variables/

**Comment by Evgen787** [comment]
@rfay 
thanks for link to kube env, but i want to pass ip addr of kube node IP, so does not pass static env to container. Can I pass dynamic var (HOST_KUBE_IP or something)?
Or i can use only static env pass to container on every kubernetes nodes?
NODE1_IP_ADDR=x.x.x.x 
NODE<N>_IP_ADDR=x.x.x.x

Now we use only docker for running our app(without kube). So we run app and register this app in consul as service through the consul client. Consul client running with advertise IP=<docker_host_ip>. 
So my services have docker host IP and I can access to this service ip (docker host ip, where is app running in docker)

**Comment by rfay** [comment]
I'm not sure, but I think you're asking for support on consul, and I just don't have any to give here. I strongly recommend that you join the consul mailing list at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/consul-tool - or just keep rephrasing the question if I'm completely misunderstanding. 

If you're looking for Kubernetes support, try their support channels (Or the wonderful Stackexchange). 

Thanks!

**Comment by Evgen787** [comment]
Thanks, kinda similar question )
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/consul-tool/kubernetes%7Csort:date/consul-tool/A-GXWH9LkpI/2Hgb7fX2BQAJ

**Comment by rfay** [comment]
Well, the answer to that question is yup, you *really* need consul clients in this exact setup (with vault). It's *normal* to have a consul client used on the vault nodes. And this implementation in this repository does that. Look at consul-agent-client on https://github.com/drud/vault-consul-on-kube/blob/master/deployments/vault-1.yaml

**Comment by rfay** [comment]
Closing this, reopen or comment if you think it's wrong.
